---
title: "Functions practice"
author: "Felicia Cruz"
date: "8/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```

```{r}
quarter_splits <- c(1.0, 1.1, 1.2, 1.1, 1.4, 1.5, 1.6, 1.4)

consectutive_times <- vector(mode = "numeric", length = length(quarter_splits) - 1)

for (i in 1:length(quarter_splits) - 1){
  half_mile <- quarter_splits[i+1] + quarter_splits[i]
  consectutive_times[i] <- half_mile
}
```

### Functions 

```{r}
birddog_sum <- function(bird, dog){
  if (bird >50){
    stop("Birds can't be that old!")
  }
  
  if (bird < 10){
    message("Cool little bird!")
  }  
  if (dog <0){
    warning("Can a dog be less than 0 pounds?")
  }
  add_birddog <- bird + dog 
  return(add_birddog)
}

birddog_sum(4, -8)
```

```{r}
say_hello <- function(friend, weekday){
  print(paste("Hello,", friend, "have a great", weekday))
}


```

```{r}
find_multiple <- function(a, b){
  my_multiplication <- a * b 
  print(my_multiplication)
}
find_multiple(6, 10)
find_multiple(10, 6) + 12

```

### Functions with conditions

```{r, eval= FALSE}
animal_age <- function(animal, age) {
  if (!animal %in% c("dog", "goat")){
    warning("Animal must be a dog or a goat.")
  }
  
  if (animal == "dog"){
    creature_age <- age * 7
  }
  
  else if (animal == "goat") {
    creature_age <- age * 4.7
  }
  
  return(creature_age)
}

animal_age("zebra", 13)
```

```{r}
adelie_gentoo <- penguins %>% 
  filter(species %in% c("Adelie", "Gentoo"))

```

```{r}
adelie_gentoo_wrong <- penguins %>% 
  filter(species == c("Adelie", "Gentoo"))

```


### Combine functions and for loops
```{r}
df_means <- function(df) {
  for (i in 1:ncol(df)){
    col_mean <- mean(df[[i]], na.rm = TRUE)
    print(paste("The mean value of", colnames(df[i]), "is", col_mean))
  }
}

# colnames(df[i]) will return that column name as a string
df_means(mtcars)
```

```{r}
# make a subset of only structural size variables from the penguins dataset for chinstraps

chinstrap_sizes <- penguins %>% 
  filter(species == "Chinstrap") %>% 
  select(bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g)


df_means(chinstrap_sizes)
df_means(penguins)
```

## condition to check class of an input 
```{r}
lunchtime <- function(tacos, price_per){
  if(is.numeric(tacos) == FALSE){
    stop("you must input a number of tacos")
  }
  tot_price <- tacos * price_per
  return(tot_price)
}

lunchtime("hello", 2.50)

```
## Example: use values from a data frame to calculate something based on user input 
This pulls from a data frame 
```{r}
# Calculate the groundwater transport rate 

gw_rate <- function(site){
  gw_slope_depth <- data.frame(sitename = c("mountain", "prairie", "desert", "beach"), 
                               depth = c(32, 41, 63, 2), 
                               slope = c(11.2, 0.4, 0.8, 2.6))
  site_select <- filter(gw_slope_depth, sitename == site)
  
  transport_rate <- 1.4 * site_select$slope + 3.6 * site_select$depth
  
  return(transport_rate)
}

gw_rate("beach") # test it 
```

### Now using switch()
This pulls from vectors 
```{r}
gw_rate_switch <- function(site) { 
  gw_slope_depth <- switch(site,
                           "mountain" = c(32, 11.2),
                           "prairie" = c(41, 0.4),
                           "desert" = c(63, 0.8),
                           "beach" = c(2, 2.6))
  
  transport_rate <- 1.4 * gw_slope_depth[2] + 3.6 * gw_slope_depth[1]
  
  return(transport_rate)
  }

gw_rate_switch("beach") 
```

### Logistic growth 

```{r}
logistic_growth <- function(K, N0, r, time) {
  Nt <- K / ( 1 + ((K - N0) / N0) * exp(-r * time))
  print(Nt)
}

logistic_growth(K = 5000, N0 = 200, r = 0.43, time = 6)

time_vec <- seq(from = 0, to = 35, by = 0.1)

bacterial_growth <- logistic_growth(5000, 200, 0.43, time_vec)

bacterial_df <- data.frame(time_vec, bacterial_growth)

ggplot(bacterial_df, aes(x = time_vec, y = bacterial_growth)) +
  geom_point() +
  labs(x = "Time",
       y = "Bacterial growth")
```


```{r}
r_seq <- seq(from = 0.20, to = 0.40, by = 0.01)

out_matrix <- matrix(ncol = length(r_seq),
                     nrow = length(time_vec))

# N0 = 100, K = 6000
for (i in seq_along(r_seq)){
  for(j in seq_along(time_vec)){
    pop <- logistic_growth(K = 6000, N0 = 100, r = r_seq[i], time = time_vec[j])
    out_matrix[j, i] <- pop # j indicates row and i indicated column to populate 
    # will populate the entire i column at each row j before advancing to the next column
  }
}

```

### Wrangling
```{r}
# glue time_vec on the first column and then give columns useful names based on rates 
# make into long form 
out_df <- data.frame(time = time_vec, out_matrix)

colnames(out_df) <- c("time", paste0("gr_", r_seq))

# make a long form (tidy version) of this data 

out_df_long <- out_df %>% 
  pivot_longer(-time, names_to = "growth_rate", values_to = "population")

ggplot(out_df_long, aes(x = time, y = population)) +
  geom_line(aes(color = growth_rate))

```

